apiVersion: apps/v1
kind: Deployment
metadata:
  name: mern-chat-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mern-chat-app
  template:
    metadata:
      labels:
        app: mern-chat-app
    spec:
      containers:
      - name: mern-chat-app
        image: sachinpanigrahi/mern_chat_app:latest
        ports:
        - containerPort: 5000
        env:
        - name: MONGO_URI
          value: "mongodb://mongo:27017/chatapp"
